export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_PLANTS_PENDING = 'REQUEST_PLANTS_PENDING';
export const REQUEST_PLANTS_SUCCESS = 'REQUEST_PLANTS_SUCCESS';
export const REQUEST_PLANTS_FAIL = 'REQUEST_PLANTS_FAIL'